{% set name = "pygments_anyscript" %}
{% set version = "1.2.1" %}
{% set sha256 = "280b9ca865d1ae82063585eca94fb05b84a3111a398278267d462bcb79de815f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools
    - pygments

test:
  imports:
    - pygments_anyscript

about:
  home: http://github.com/AnyBody/pygments-anyscript
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pygments lexer and style for the AnyScript language'

  description: |
    pygments_anyscript adds a plugin for Pygments to with a lexer and a style 
    for the AnyScript language. AnyScript is the scripting langugage used for 
    the AnyBody Modeling System; a system for multibody musculoskeletal 
    analysis.

  doc_url: https://github.com/AnyBody/pygments-anyscript
  dev_url: https://github.com/AnyBody/pygments-anyscript

extra:
  recipe-maintainers:
    - melund
    - MateiSarivan
    - KasperPRasmussen
