travis:
  secure:
    BINSTAR_TOKEN: DlFHbnml/PfopgiOGAtRgqkkXFEnduv1QSyDAdFCdfCR74yI67VWffUzZvJsrEA9ztn9GDw2N4LlUn+tBsvSPvUFSpopXM1FIwu5ngiiustnwGqZIXAVaArIWtaBaStFfZje5FD85nRsfSDu4tAhLRxC70IycsZfm5Qb6HWoArTJ7REgqpKYkGWtfQsmyOyHxc2IUe/ssP1QxUAmONw7WyNKzA6vFVu3auAFWezUJJjkEtYeTrprLqMcr6I0peALUE0XdS5dA0oZEBqDpfXPTA7avCLx/utrXUwX8UWT6gksF3On4HN0I4Pir3CrPmaP1q26JfwgVUKLMGwj4F1nHg10uqmZ+bw8shXSFvPtXg0S9lI3sLtnxVEbWxm2gsnxkMiXGakYHnAYyDkiysvoOF3kFFsjkCjZnyFIDNZ5B9bJsZgrvRhRNngbaJgYp3/3WVRG/Kv0g5afhGNCo2TDKjGaimCRTznYHirHJqbA96tHBVxWHQXoQn53EYKVEXx11ObPeFjlDOL72mJl2AtcQ0Q4scMETxLbgnJ1kSeb8QN6Rc0KUaj7Vj3Ey+NyqmqhsCPUDqdJVfop4+ypYpAn4xyI7LPxCy3SbOJ5UllbZkayd36vjBL4T9gd/sJAatBrjR3P/aPPlwafsEaxEwfQ5LXhFp2C7aX5chBEPXtbiNc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
