travis:
  secure:
    BINSTAR_TOKEN: CpqsTWh3t0OvXdzUn1WYjlKddZ8xmFYavho+XalE/2i08CXIiE5p2rMu4n6hnMcRtKaHFQ8f84E4OCYYkU+vY+9aPn5ZGlQqmqkFC2RvjgYClc5gUTIH7bOfj6fwig9eR53xh4rAlOHBSJdC1gRpmPFrvvZ31wN/BuV7jfQryAlLSaPUOAN/zuK1Q/Q8hMn3FCsNxOHLVPv8bs8m9Bsg8vv+5KU+jdkitDW+hJo8phvA/+hqk6kywUb5GvHqkqPPYHrNLHJ0lVzSF6ILlqlrdzs8zlw4skxncccQRsydVNlXlpFT/0cZNy9ZzZ3GMPB9PTNXBxucpWLlJ+58y9m6IQ5qHdQC0v/qq0QiFMohFNu6zcqpWEk7w31SAAiGW8CUWcqcASY/wRNOhD72E0QfBWnaEWcXE4831H3Yz4IM1EzSIcChokcZpEJRcLx3WY6G5DBjo0Xz9n/4DM73e2qArRs/vtusORylxdp+wuzAxymMnOtv6o9RR9799PLfmoMVHnvIXJ3Wr5ZiM8FtsmVV+p6kJntRG1BH768W/I40xGEPCnYmaab+yW7I71lziNEVeTOubJv5vdszZHzueXwPAr/awJ4gE7wqBYrCWwWWxr+Eksg71OAWFBYO/McUUy4x8EmWOBGiK6d37n8bK3nhKoNA9PSZa3pYLhsZp/zBC70=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
